sudo: required
language: java
services:
- docker
env:
  global:
    - secure: jkiP/TEDZqQX6+qQ2BIQgsHN18l+1akY89Uxblw8ES//7Kqw3QSP+ybQfFmukc5FBIN03vwiOOyK3Sww+XLf3OcS8i55kXLg9QeyKAZIwsrU0pBTx0FJuVHNRcmmOkfitV0K4nd8BcrF9yPOLbw63vKJiChAt1dcivJcZ0AqfCDPacK+oSCbTgbaPCmD+HxSO+x+APIDk0bAnoDJXqAt2pv2lqrebf0pWhR/bZ9lHsmhnWDCCVkXqgMLk2dz/mSzO0U1Yae1VbLXzSUPqekzjpzSWci/YFBiXvByNigEm5maBSkJJQblmQ9jgZH+7vCs/ZMFyzX/0EDFL89Qxj5Tvfco3gQc7VJWZAkdd5+gOAVkTiidlzVW/lHqvOMhxuaruY/gxJgPDvb+AH6se2ZttNkKecaQVIri25jWR6xR6yzShQszZK1P9fAavZBdiLL0U8NtJ+3WcG7Ckqkq8A5bmNXPDXhlbuOLklwY5q9a6zpAiQD1TXc87+Yy3slrkBVRrRni/8dWKyexZWrZcj0SxMyl5UuFxpCdIWbWrCtFiYWfRqQPByg4vAPKLoPRAbhlcCzj5/FRT2I+v7yxb6H9Z0PWAFI9+bvBYiLCWBEowBeeV4S8sGjlUlmzT7yz9K8k7iN2TsOeXKjFCjCtMuzzz/18HUefOpwnqJUGABcleMw=
    - secure: Ai8q8d/nhkKI5kgHTivJm5fOVsDc1uKkvzytQ0SS5oMVA1lwCX3NaNRLLp8TEUUuMGcX/dR2d88dEf+YLkXGlCTMgvnphFVOKU1Wx1UatmseTv6jw0HV/QpxYeL1EsxBNxPnisDfZsldnsaij80Y+uymrAF+a0j+lTrBePPhTZ991aUsT0R92wnaMUo/xtaX9YNQr5jdJQ0iQe+vx6mhcVxMoS9aqIy9DWqQWTWsiZE6cD8eri4svqxHPaTo+FnJCzCy1T0qjn6UETE/R/C4XQNINpw6RrK1XoRXZWLHDFTVj2yyybCZyTjG6CsIYg6j6YiAakwpjcGQxEY3hqKuUNP5fNhqvHOshuFFMkoMbZdmAx4F8uiEuTA/kPqzu4+tijTCdCBr0bO3L3XYaUxd2p6jsXt8WyDSv+JIgrVOEMUvOA/GavxPsgkbOdIgjuelHgOoOOjNM2fb+GgFARlmCP+P2rVbLBj/FugoUti71VdnyNSEN0JA6+R/QsVLk2KVSKKiBzFfkgRRIiKjkzSBx8ENeDyGIeO0rHesNjJMmy5X0BP99QwcdhWcc4nBbj1RToDHcFEhQ5s2GAZeCVJn7r8esFSwL+SlSFWHknueGlhGTm4gT7bSdhqky7e59s5xzWSDvwUssvR1R9c7qnWSZFrKBxQWcyibd0gLB1iovec=
before_install:
- curl -sL https://github.com/nais/naisd/releases/download/127.0.0/nais-127.0.0-linux-amd64.xz | xz -d > nais && chmod +x nais
before_script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
script:
- "./mvnw test -B"
- nais validate -f hiv/nais.yaml
- nais validate -f hoi/nais.yaml
- nais validate -f testapi/nais.yaml
after_success:
- "./mvnw com.spotify:dockerfile-maven-plugin:push -pl '!dto'"
branches:
  only:
  - master
notifications:
  email: false
