sudo: required
language: java
services:
- docker
env:
  global:
    - secure: "BmmMkxKN1+j6HsVT8P1tHrDK/L6ytUGmcWwwF/7i9LLeWuOO7s8EBN8glDURDTK62kbRkYqbv4yKabQqWnH8T5mKMFsqP1+4odgcM29UR264mh+onUms+xlexxW/AouRQOHCK9teFNGz1ZQBW1ee0CtNNzmiZ3OntL95ilRJZpNX2n3jqpz6uAXg7A4hh7A79tEARUISqfB1wnMlLWRtYGOyeGDFBzTc2mA15aYyTpwd7JHYnrd4opYfJEgQ8qjSjFvI6s8quUsJanKpOTCC7iOneRJBsmqT3zNYIxKLnODgJtRD83/4crgNzt/uUhUzZQrmj9Oe4orm8t9wwIY39NgWmN5gwm4og7NFX5SeUUSPpy96JKqv4eZ/dLbrJ3XWFezboQpdl71fwqitJ+rWCuDbWovZiXgYoaP2rbuXJers4+MVtkSKhmdwzLtThiZQGNivj74G+8K7Jbmxf58suam5iMR1M1nJzgPB0K3iMbg7WPm0NA/ls1lrrRfHWlfmiQXYzyJdVx6WPvtKA91Uff3QxMHdPC5ZgFU/H5+hKFPZzMggk8J8qWeIadZW9F/674/Fjk9/2pmoki8Mn8aakhE/renUSYbxL+qDy0Wefs9LAsolhQ5je3Ry/uh1pq2ev7e9NI0gpRv+9fO5JUBh80Jn5YZZQRNn3bA91S1qjXY="
    - secure: "Ai8q8d/nhkKI5kgHTivJm5fOVsDc1uKkvzytQ0SS5oMVA1lwCX3NaNRLLp8TEUUuMGcX/dR2d88dEf+YLkXGlCTMgvnphFVOKU1Wx1UatmseTv6jw0HV/QpxYeL1EsxBNxPnisDfZsldnsaij80Y+uymrAF+a0j+lTrBePPhTZ991aUsT0R92wnaMUo/xtaX9YNQr5jdJQ0iQe+vx6mhcVxMoS9aqIy9DWqQWTWsiZE6cD8eri4svqxHPaTo+FnJCzCy1T0qjn6UETE/R/C4XQNINpw6RrK1XoRXZWLHDFTVj2yyybCZyTjG6CsIYg6j6YiAakwpjcGQxEY3hqKuUNP5fNhqvHOshuFFMkoMbZdmAx4F8uiEuTA/kPqzu4+tijTCdCBr0bO3L3XYaUxd2p6jsXt8WyDSv+JIgrVOEMUvOA/GavxPsgkbOdIgjuelHgOoOOjNM2fb+GgFARlmCP+P2rVbLBj/FugoUti71VdnyNSEN0JA6+R/QsVLk2KVSKKiBzFfkgRRIiKjkzSBx8ENeDyGIeO0rHesNjJMmy5X0BP99QwcdhWcc4nBbj1RToDHcFEhQ5s2GAZeCVJn7r8esFSwL+SlSFWHknueGlhGTm4gT7bSdhqky7e59s5xzWSDvwUssvR1R9c7qnWSZFrKBxQWcyibd0gLB1iovec="
    - secure: "LiSjF2YYGv61/FQP96PqM12S47q52g93zPh9ln6IVpAaNvDewkCzW0bTpYAwSmlKP2IJ5Wr3wAnAyH9RcycYk7IqYr2BOtTNDJ/9mB+SHMNXYiVABbDcrwnWdb915le271LyrbR9f/DU7S2Hb1c/jizKFskJkCkXIh/9okP7lh/bIZqiuxImuWDGJxOwMggjqScV02kfMlZy/+n4/QpZsVLvPMyY/hKcCJIawQOSJf57HidRzZkA62HC608Uy+2zFQ+192LP1oF0SVfS3LxkfKjIIO1xJMU1uAEOq3CHni8RNIKzNfDtw4ZC5l2BgMTcIaJF57OyReY10Sp3U0U1BztLLsK1mjnwMfjhidsuibtUijlkguVruzD7Pdtvj1VG/iaJ95+stpycm1fOHg7BMzkJiqzCvMKC8M9GfOhrkX/QLbNLKYaWWv0Py2ylRRNGSurZ9tjr6OHuMJa2NrQDmKTHOqbh/k1b1IvNnshmpkSfUOH+br7FjIU4njhsaoDHTvUx+l5UzVVxEBEVYeEAH4LnQxmlgmz8uCTCDsQShLZCLo2LS8K+20gbn3oLFZXYULzWX0g2UL16u6oFTYxNVgohwvjcUJUhe8EDnWxWvmiRsEFCx8FagCJuNeiHHERKqK88aPnD6nPtwh2KHG/vwi7zZzGbKQMp6NNxJsBdYXo="
addons:
  apt:
    packages:
      - docker-ce
before_install:
- curl -sL https://github.com/nais/naisd/releases/download/127.0.0/nais-127.0.0-linux-amd64.xz | xz -d > nais && chmod +x nais
- git config user.name navikt-ci
- git config user.email 32665735+navikt-ci@users.noreply.github.com
before_script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
script:
- CURRENT_VERSION=$(cat VERSION) && echo $((CURRENT_VERSION+1)) > VERSION
- NEW_VERSION=$(cat ./VERSION) && ./mvnw versions:set -DnewVersion=$NEW_VERSION -DartifactId='*' -DgenerateBackupPoms=false
- "./mvnw test -B"
- ./nais validate -f hiv/nais.yaml
- ./nais validate -f hoi/nais.yaml
- ./nais validate -f testapi/nais.yaml
after_success:
- NEW_VERSION=$(cat ./VERSION) && git commit -am "Bump version to $NEW_VERSION [skip ci]"
- git tag -a $(/bin/cat ./VERSION) -m "auto-tag from Travis CI [skip ci]" && git push --tags https://$GH_TOKEN@github.com/navikt/tortuga HEAD:master
- "./mvnw com.spotify:dockerfile-maven-plugin:push -pl 'hiv,hoi,testapi'"
branches:
  only:
  - master
notifications:
  email: false
